const fs = require("fs");
const path = require("path");

const ARTIFACT_PATH = path.join(
  __dirname,
  "..",
  "artifacts",
  "contracts",
  "OrbiTrustRegistry.sol",
  "OrbiTrustRegistry.json"
);
const OUT_DIR = path.join(__dirname, "..", "lib", "contract");
const OUT_PATH = path.join(OUT_DIR, "abi.ts");

function exportAbi() {
  if (!fs.existsSync(ARTIFACT_PATH)) {
    throw new Error(
      `Artifact not found at ${ARTIFACT_PATH}. Run \`npm run compile\` first.`
    );
  }
  const artifact = JSON.parse(fs.readFileSync(ARTIFACT_PATH, "utf8"));
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const banner =
    "// AUTO-GENERATED by scripts/export-abi.js - do not edit by hand.\n" +
    "// Regenerate with `npm run export-abi` (runs automatically after `npm run compile`).\n";
  const body = `export const orbiTrustAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;

  fs.writeFileSync(OUT_PATH, banner + body);
  console.log(`[export-abi] Wrote ABI -> ${path.relative(process.cwd(), OUT_PATH)}`);
  return OUT_PATH;
}

if (require.main === module) {
  try {
    exportAbi();
  } catch (err) {
    console.error("[export-abi]", err.message);
    process.exit(1);
  }
}

module.exports = { exportAbi };
